### ISSUE TITLE
Cannot download csv

### ISSUE THREAD

**Issue by onharman** [alexandersimoes/oec#72] opened 2015-04-18 12:26 UTC
Hello, in the explore section if I go on export by product I cannot download the csv data. I tried multiple browsers.
The error message displayed is 
Method Not Allowed

The method is not allowed for the requested URL.

Thank you very much

**Comment by davelandry** [comment] 2015-04-19 21:18
Duplicate of #71

**Closed by davelandry** 2015-04-19 21:18 UTC
